
name: 'recurly'
version: '1.0'

source-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]
data-paths: ["data"]

models:
  recurly:
    vars:
      subscriptions_table:          #table.schema
      invoices_table:               #table.schema
      invoices_line_items_table:    #table.schema
